# **homework assignments**

1.Pythone Basics

Data types:


In [ ]:
a = ("rohan")
b = (23)
c = (25.5)
d = (True)
print (type(a))
print (type(b))
print (type(c))
print (type(d))


<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


In [ ]:
# converting int to float
b = 23
print (float(b))

# converting string to int
a = "23"
print (int(a))

# converting float to int
c = 25.5
print (int(c))


23.0
23
25


**Operators:**

In [ ]:
#Python Arithmetic Operators

a = 50
b = 25


print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)
print(a**b)

75
25
1250
2.0
0
2
2980232238769531250000000000000000000000000


In [ ]:
# Python Comparison Operators
e = 8
f = 5

print(e == f)
print(e != f)
print(e > f)
print(e < f)
print(e >= f)
print(e <= f)

False
True
True
False
True
False


In [ ]:
# Python Logical Operators
r = 8
s = 5
t = 10

print(r > s and r < t)
print(r > s or r == t)
print(not(r > s and r < t))

True
True
False


**#control flow**

**calculator**

In [ ]:
print('''select opretor
1.add
2.substrick
3.multiply
4.divide''')

num1 = int(input("enter a number 1: "))
num2 = int(input("enter a number 2: "))
opretor = input("enter a opretor:(+,-,*,/,) ")

if opretor == '+':
  print(num1+num2)

elif opretor == '-':
  print(num1-num2)

elif opretor == '*':
  print(num1*num2)

elif opretor == '/':
  print(num1/num2)

else:
  print("invalid opretor")


select opretor
1.add
2.substrick
3.multiply 
4.divide
enter a number 1: 98
enter a number 2: 76
enter a opretor:(+,-,*,/,) /
1.2894736842105263


# **2. NumPy**

**arrays**

In [ ]:
import numpy as np

r1 = np.array([1,2,3,4,5,6])    # 1d arreys
print(r1)
print(type(r1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
r2 = np.array([[1,2,3],[4,5,6]])   # 2d arreys
print(r2)
print(type(r2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
r3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])   # 3d arreys
print(r3)
print(type(r3))



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


In [ ]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]


array([1, 3, 5])

In [ ]:
x[-2:10]

array([8, 9])

In [ ]:
x[5:]

array([5, 6, 7, 8, 9])

In [ ]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
x[1, 1:4]

array([7, 8, 9])

In [ ]:
x = np.array(np.reshape(np.arange(1,13),(3,4),'F'))
x


array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

.array **atributes**

In [ ]:

r5 = np.array([[1, 2, 3],
                [4, 2, 5]])

# Printing type of arr object
print("Array is of type: ", type(r5))

# array dimensions (axes)
print( r5.ndim)

#  shape of array
print( r5.shape)

#  size (total number of elements) of array
print( r5.size)

# type of elements in array
print( r5.dtype)

Array is of type:  <class 'numpy.ndarray'>
2
(2, 3)
6
int64


**Array methods**

In [ ]:
import numpy as np
array = np.arange(10)
print(array)

r1 = np.mean(array)
print("\nMean: ", r1)

r2 = np.median(array)
print("\nMedian: ", r2)

r3 = np.std(array)
print("\nStandard Deviation: ", r3)


[0 1 2 3 4 5 6 7 8 9]

Mean:  4.5

Median:  4.5

Standard Deviation:  2.8722813232690143


# **3. Pandas**