# **numpy functions **

In [2]:
# import numpy

import numpy as np

In [ ]:
# version chek for pc

np.__version__

'1.26.4'

In [8]:
f1=np.array([1,2,3,4,5,6])
print(f1)
print(type(f1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [9]:
f1=np.array(([1,2,3],[4,5,6]))
print(np.ndim(f1))  # 2d array
print(np.shape(f1))  #(2 rows , 3 columns)
print(np.size(f1))    # multyply by 2 rows and 3 colums


2
(2, 3)
6


# **array creation zeros and ones**

In [10]:
zeros=np.zeros((3,4))
ones=np.ones((4,4))
print(zeros)
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
zeros=np.zeros((3,4))
ones=np.ones((4,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])